# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"

  config.omnibus.chef_version = :latest

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "YOUR_ACCESS_KEY_ID"
    aws.secret_access_key = "YOUR_SECRET_ACCESS_KEY"
    aws.keypair_name = "YOUR_KEYPAIR"

    aws.region = "eu-west-1"

    aws.ami = "ami-f0b11187"
    aws.instance_type = "t2.micro"

    aws.security_groups = ['webservice']

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "PATH_TO_KEYPAIR.PEM"
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"
    chef.add_role "prod"
  end

  config.vm.synced_folder "../server/", "/home/ubuntu/server"
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
