# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provider VIRTUAL-BOX
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  #Provision virtual environment
  #config.vm.provision "chef_solo" do |chef|
  #  chef.cookbooks_path = "../chef/cookbooks"
  #  chef.roles_path = "../chef/roles"
  #  chef.environments_path = "../chef/environments"
  #  chef.environment = "dev"
  #  chef.add_role "web_server"
  #end

  #Synced folders
  # config.vm.synced_folder "../server/", "/home/vagrant/server"
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
